import React, { createContext, useState, useEffect, useContext } from 'react';

const LanguageContext = createContext(null);

const dictionary = {
  // Common / Sidebar
  'Trang chủ': 'Home',
  'Tìm kiếm': 'Search',
  'Thư viện': 'Library',
  'Phân tích': 'Analytics',
  'Quản lý tải nhạc': 'Upload Manage',
  'Quản trị': 'Admin Control',
  'Thông báo': 'Notifications',
  'Tải nhạc lên': 'Upload Music',
  'Đăng xuất': 'Logout',
  'Đăng nhập': 'Sign In',

  // Header
  'Tìm kiếm bài hát, nghệ sĩ...': 'Search songs, artists...',
  'Tìm kiếm...': 'Search...',
  'Tìm kiếm trong danh sách phát...': 'Search in playlist...',
  'Tìm kiếm bài hát...': 'Search songs...',
  'Tìm kiếm trong thư viện...': 'Search in library...',
  'Thông báo': 'Notifications',
  'Cài đặt tài khoản': 'Account Settings',
  'Đăng xuất': 'Logout',
  'Ngôn ngữ': 'Languages',

  // MusicPlayer
  'Không có bài hát': 'No song selected',
  'Chọn nhạc để phát': 'Choose music to play',

  // Home
  'Đang tải giai điệu...': 'Loading melodies...',
  'MỚI PHÁT HÀNH': 'NEW RELEASE',
  'Âm Thanh Của Tương Lai': 'Sound of the Future',
  'Khám phá album mới nhất từ nhóm nhạc indie-electronic "Ethereal Echoes". Một hành trình âm nhạc xuyên không gian và thời gian.': 'Discover the latest album from indie-electronic group "Ethereal Echoes". A musical journey across space and time.',
  'Nghe Ngay': 'Listen Now',
  'Xem Thư Viện': 'View Library',
  'Gợi Ý Cho Bạn': 'Recommended For You',
  'Phù hợp sở thích': 'Matches your taste',
  'Bảng Xếp Hạng': 'Charts',
  'Top Lượt Nghe': 'Top Views',
  'lượt nghe': 'views',
  'Mới Cập Nhật': 'Newly Updated',
  'Mới Nhất': 'Latest',
  'Chào mừng trở lại,': 'Welcome back,',
  'Bạn đã đăng nhập hệ thống với vai trò': 'You are logged in with the role of',
  'Khám phá hàng ngàn giai điệu và quản lý trải nghiệm cá nhân của mình ngay hôm nay.': 'Explore thousands of melodies and manage your personal experience today.',
  'Xem danh sách phát của tôi': 'View my playlists',

  // Settings
  'Đổi ảnh đại diện': 'Change avatar',
  'Gỡ ảnh': 'Remove image',
  'Bạn có chắc chắn muốn gỡ ảnh đại diện không?': 'Are you sure you want to remove your avatar?',
  'Gỡ ảnh đại diện thất bại.': 'Removing avatar failed.',
  'Cập nhật ảnh đại diện thất bại.': 'Updating avatar failed.',
  'Thông tin tài khoản': 'Account Information',
  'Họ và tên': 'Full Name',
  'Địa chỉ Email': 'Email Address',
  'Cập nhật thông tin thành công!': 'Account information updated successfully!',
  'Cập nhật thông tin thất bại.': 'Updating information failed.',
  'Họ và tên không được để trống.': 'Full name cannot be empty.',
  'Đang cập nhật...': 'Updating...',
  'Cập nhật thông tin': 'Update Information',
  'Đổi mật khẩu': 'Change Password',
  'Mật khẩu hiện tại': 'Current Password',
  'Mật khẩu mới': 'New Password',
  'Mật khẩu hiện tại và mật khẩu mới là bắt buộc.': 'Current and new passwords are required.',
  'Mật khẩu mới phải tối thiểu 8 ký tự.': 'New password must be at least 8 characters.',
  'Đổi mật khẩu thành công!': 'Changed password successfully!',
  'Thay đổi mật khẩu thất bại.': 'Changing password failed.',
  'Đang xác nhận...': 'Confirming...',
  'Xác nhận thay đổi': 'Confirm Changes',
  'Thông tin thanh toán': 'Payment Information',
  'Thêm phương thức': 'Add Method',
  'Thêm phương thức thanh toán': 'Add Payment Method',
  'Mặc định': 'Default',
  'Đặt mặc định': 'Set Default',
  'Xóa thẻ': 'Delete Card',
  'Chưa có phương thức thanh toán nào.': 'No payment methods yet.',
  'Xóa tài khoản': 'Delete Account',
  'Việc xóa tài khoản sẽ gỡ bỏ vĩnh viễn tất cả danh sách phát, bài hát đã tải lên và lịch sử nghe nhạc của bạn. Hành động này không thể hoàn tác.': 'Deleting your account will permanently remove all of your playlists, uploaded songs, and listening history. This action cannot be undone.',
  'Tiếp tục xóa tài khoản': 'Continue to delete account',
  'Cảnh Báo Xóa Tài Khoản': 'Account Deletion Warning',
  'Bạn có chắc chắn muốn xóa vĩnh viễn tài khoản này không? Hành động này sẽ xóa toàn bộ danh sách phát, bài hát đã tải lên và không thể hoàn tác.': 'Are you sure you want to permanently delete this account? This action will remove all playlists, uploaded songs, and cannot be undone.',
  'Hủy bỏ': 'Cancel',
  'Xác nhận xóa': 'Confirm Delete',
  'Số thẻ': 'Card Number',
  'Tên chủ thẻ': 'Cardholder Name',
  'Mã bảo mật (CVV)': 'Security Code (CVV)',
  'Hạn sử dụng': 'Expiry Date',
  'Đặt làm phương thức thanh toán mặc định': 'Set as default payment method',
  'Thêm thẻ': 'Add Card',
  'Đang thêm...': 'Adding...',
  'Số thẻ phải chứa 15 hoặc 16 chữ số.': 'Card number must contain 15 or 16 digits.',
  'Vui lòng nhập tên chủ thẻ.': 'Please enter cardholder name.',
  'Mã CVV phải chứa 3 hoặc 4 chữ số.': 'CVV code must contain 3 or 4 digits.',
  'Hạn sử dụng phải có định dạng MM/YYYY (Ví dụ: 12/2026).': 'Expiry date must be in MM/YYYY format (e.g. 12/2026).',
  'Thêm thẻ thất bại.': 'Adding card failed.',
  'Đặt thẻ mặc định thất bại.': 'Setting default card failed.',
  'Xóa thẻ thất bại.': 'Deleting card failed.',
  'Bạn có chắc chắn muốn xóa phương thức thanh toán này không?': 'Are you sure you want to delete this payment method?',

  // PlaylistDetail / Library
  'Đang tải danh sách phát...': 'Loading playlist...',
  'Không tìm thấy danh sách phát này hoặc bạn không có quyền xem.': 'This playlist was not found or you do not have permission to view it.',
  'Quay lại thư viện': 'Back to library',
  'Riêng tư': 'Private',
  'Công khai': 'Public',
  'Không có mô tả cho danh sách phát này.': 'No description for this playlist.',
  'bài hát': 'songs',
  'Khoảng ': 'About ',
  'phút': 'minutes',
  'giờ': 'hours',
  'Phát ngay': 'Play now',
  'Trộn bài': 'Shuffle',
  'Thêm bài hát': 'Add song',
  'Chỉnh sửa': 'Edit',
  'Xóa playlist': 'Delete playlist',
  'Tiêu đề': 'Title',
  'Album': 'Album',
  'Ngày thêm': 'Date added',
  'Chưa có bài hát nào trong playlist này.': 'No songs in this playlist yet.',
  'Thêm bài hát mới': 'Add new song',
  'Thể loại': 'Genre',
  'Thêm vào': 'Add to',
  'Thêm': 'Add',
  'Không có bài hát nào phù hợp để thêm.': 'No suitable songs to add.',
  'Chỉnh sửa Playlist': 'Edit Playlist',
  'Tên Playlist': 'Playlist Name',
  'Nhập tên playlist...': 'Enter playlist name...',
  'Mô tả': 'Description',
  'Nhập mô tả ngắn...': 'Enter a short description...',
  'Quyền truy cập': 'Access Rights',
  'Ảnh bìa mới (Tùy chọn)': 'New cover image (Optional)',
  'Lưu thay đổi': 'Save changes',
  'Cảnh Báo Xóa': 'Delete Warning',
  'Bạn có chắc chắn muốn xóa danh sách phát': 'Are you sure you want to delete the playlist',
  'không? Hành động này không thể hoàn tác.': '? This action cannot be undone.',
  'Không thể xóa bài hát khỏi playlist.': 'Cannot remove song from playlist.',
  'Không thể thêm bài hát vào playlist.': 'Cannot add song to playlist.',
  'Không thể xóa danh sách phát.': 'Cannot delete playlist.',
  'Cập nhật playlist thất bại.': 'Updating playlist failed.',
  'Chưa rõ': 'Unknown',
  'thg 1': 'Jan',
  'thg 2': 'Feb',
  'thg 3': 'Mar',
  'thg 4': 'Apr',
  'thg 5': 'May',
  'thg 6': 'Jun',
  'thg 7': 'Jul',
  'thg 8': 'Aug',
  'thg 9': 'Sep',
  'thg 10': 'Oct',
  'thg 11': 'Nov',
  'thg 12': 'Dec',
  
  // LibraryPlaylists
  'Đang tải thư viện của bạn...': 'Loading your library...',
  'Thư viện của bạn': 'Your Library',
  'Quản lý các bản nhạc, danh sách phát và nghệ sĩ yêu thích.': 'Manage your favorite tracks, playlists, and artists.',
  'Tạo Playlist': 'Create Playlist',
  'Nghệ sĩ đang theo dõi': 'Following Artists',
  'Bạn chưa theo dõi nghệ sĩ nào.': 'You are not following any artists yet.',
  'Danh sách phát của tôi': 'My Playlists',
  'Danh sách phát yêu thích': 'Favorite Playlists',
  'Không có mô tả': 'No description',
  'Bạn chưa tạo danh sách phát nào.': 'You haven\'t created any playlists yet.',
  'Tạo ngay playlist đầu tiên': 'Create your first playlist',
  'Bạn chưa thích danh sách phát nào.': 'You haven\'t liked any playlists yet.',
  'Bài hát yêu thích': 'Favorite Songs',
  '# Tiêu đề': '# Title',
  'Thao tác': 'Action',
  'Không có bài hát yêu thích nào.': 'No favorite songs yet.',
  'Tạo Playlist Mới': 'Create New Playlist',
  'Đang tạo...': 'Creating...',
  'Tạo playlist thất bại.': 'Failed to create playlist.',
  'Ảnh bìa (Tùy chọn)': 'Cover image (Optional)',

  // ArtistDetail
  'Đang tải thông tin nghệ sĩ...': 'Loading artist info...',
  'Không tìm thấy nghệ sĩ này.': 'Artist not found.',
  'Không tìm thấy thông tin nghệ sĩ này.': 'Artist details not found.',
  'Quay lại trang chủ': 'Go back to Home',
  'Nghệ sĩ xác minh': 'Verified Artist',
  'PHÁT NGHE': 'PLAY',
  'Không có nhạc': 'No Music',
  'ĐANG THEO DÕI': 'FOLLOWING',
  'THEO DÕI': 'FOLLOW',
  'Danh sách bài hát': 'Songs List',
  'Nghệ sĩ chưa có bài hát nào được duyệt.': 'No approved songs from this artist.',
  'Giới thiệu': 'About',
  'Người hâm mộ cũng thích': 'Fans Also Like',
  'Nghệ sĩ': 'Artist',
  'Người theo dõi': 'Followers',
  'Bài hát phổ biến': 'Popular Songs',
  'Theo dõi': 'Follow',
  'Đang theo dõi': 'Following',
  'Không có bài hát nào được tải lên bởi nghệ sĩ này.': 'No songs uploaded by this artist.',
  ' là một nghệ sĩ sáng tạo, đam mê tạo ra các cung bậc cảm xúc âm nhạc đỉnh cao. Sự kết hợp khéo léo giữa ca từ sâu lắng và các giai điệu tinh tế đem lại một làn sóng mới cho người hâm mộ.': ' is a creative artist, passionate about creating top-notch musical emotions. The clever combination of deep lyrics and delicate melodies brings a new wave to fans.',

  // SearchResults
  'Bạn muốn nghe gì?': 'What do you want to listen to?',
  'Kết quả tìm kiếm cho:': 'Search results for:',
  'Tất cả': 'All',
  'Kết quả hàng đầu': 'Top Result',
  'Bài hát khớp tìm kiếm': 'Matching Songs',
  'Nghệ sĩ liên quan': 'Related Artists',
  'Đang Follow': 'Following',
  'Không tìm thấy bất kỳ kết quả nào khớp với': 'No results found matching',
  'Hãy thử kiểm tra lỗi chính tả hoặc tìm kiếm bằng từ khóa khác.': 'Please try checking for spelling errors or searching with other keywords.',
  'Đang tìm kiếm...': 'Searching...',
  'Kết quả tìm kiếm cho': 'Search results for',
  'Bài hát': 'Songs',
  'Chưa tìm thấy bài hát nào phù hợp.': 'No matching songs found.',
  'Nghệ sĩ': 'Artists',
  'Chưa tìm thấy nghệ sĩ nào phù hợp.': 'No matching artists found.',
  'Không tìm thấy kết quả phù hợp.': 'No matching results found.',
  'Xem thêm': 'See more',

  // NotificationsSocial
  'Đang tải thông báo...': 'Loading notifications...',
  'Thông báo & Mạng xã hội': 'Notifications & Social',
  'Đang nghe': 'Listening',
  'Đã nghe': 'Listened',
  'Đánh dấu tất cả là đã đọc': 'Mark all as read',
  'Bạn không có thông báo nào mới.': 'You have no new notifications.',
  'Mới': 'New',
  'Hoạt động bạn bè': 'Friend Activity',
  'Hôm nay': 'Today',
  'Vừa xong': 'Just now',
  'phút trước': 'mins ago',
  'giờ trước': 'hours ago',
  'ngày trước': 'days ago',
  '5 phút trước': '5 mins ago',
  '1 giờ trước': '1 hour ago',
  'Theo dõi các hoạt động mới và yêu cầu theo dõi nghệ sĩ từ người dùng khác.': 'Follow new activities and artist follow requests from other users.',
  'Yêu cầu theo dõi': 'Follow Requests',
  'đã gửi yêu cầu theo dõi bạn.': 'sent you a follow request.',
  'Chấp nhận': 'Accept',
  'Từ chối': 'Decline',
  'Chưa có yêu cầu theo dõi nào.': 'No follow requests yet.',
  'Hoạt động mới': 'New Activities',
  'Không có hoạt động mới nào.': 'No new activities.',
  'Chấp nhận yêu cầu thành công!': 'Request accepted successfully!',
  'Từ chối yêu cầu thành công!': 'Request declined successfully!',

  // UploadManage
  'Đang tải danh sách bài hát...': 'Loading songs list...',
  'Quản lý tải nhạc': 'Upload Music Management',
  'Tải lên các bản nhạc mới và quản lý các bài hát đã phân phối.': 'Upload new tracks and manage distributed songs.',
  'Tải nhạc lên': 'Upload Music',
  'Tên bài hát': 'Song Title',
  'Nhập tên bài hát...': 'Enter song title...',
  'Chọn nghệ sĩ': 'Select Artist',
  'Thể loại': 'Genre',
  'Nhập thể loại...': 'Enter genre...',
  'Chọn file âm thanh': 'Select Audio File',
  'Chọn file ảnh bìa': 'Select Cover File',
  'Đang tải lên...': 'Uploading...',
  'Tải lên bài hát': 'Upload Song',
  'Bài hát đã phân phối': 'Distributed Songs',
  'Chưa có bài hát nào được tải lên.': 'No songs uploaded yet.',
  'Nhập tên bài hát': 'Enter song title',
  'Nhập thể loại': 'Enter genre',
  'Lưu': 'Save',
  'Xóa bài hát': 'Delete Song',
  'Bạn có chắc chắn muốn xóa bài hát': 'Are you sure you want to delete the song',
  'không?': '?',
  'Tải lên thành công!': 'Upload successful!',
  'Cập nhật thành công!': 'Update successful!',
  'Xóa bài hát thành công!': 'Delete song successful!',
  'Vui lòng điền đầy đủ tiêu đề, thể loại và chọn file âm thanh, ảnh đại diện.': 'Please fill in all details and select both audio and cover files.',
  'Tải bài hát lên thành công! Đang chờ kiểm duyệt từ Admin.': 'Song uploaded successfully! Waiting for Admin approval.',
  'Tải bài hát lên thất bại.': 'Failed to upload song.',
  'Bạn có chắc chắn muốn xóa bài hát này?': 'Are you sure you want to delete this song?',
  'Xóa bài hát thất bại.': 'Failed to delete song.',
  'Tìm kiếm trong kho bài hát...': 'Search in song repository...',
  'Tải lên bài hát mới': 'Upload new song',
  'Chia sẻ tác phẩm âm nhạc mới của bạn. Tác phẩm chất lượng cao của bạn xứng đáng một ngôi nhà cao cấp.': 'Share your new music. Your high quality work deserves a premium home.',
  'Chọn thể loại': 'Select genre',
  'Chế độ hiển thị': 'Visibility mode',
  'Lời bài hát (Tùy chọn)': 'Lyrics (Optional)',
  'Viết lời bài hát tại đây...': 'Write lyrics here...',
  'Click để chọn file .mp3 hoặc .wav': 'Click to select .mp3 or .wav file',
  'File đã tải lên thành công': 'File uploaded successfully',
  'Click để chọn ảnh bìa (Tỷ lệ 1:1)': 'Click to select cover image (1:1 ratio)',
  'Ảnh đã tải lên thành công': 'Image uploaded successfully',
  'Thay đổi ảnh bìa': 'Change cover image',
  'Đang xuất bản': 'Publishing',
  'Xuất bản bài hát': 'Publish Song',
  'Đang xử lý file nhạc...': 'Processing music file...',
  'Bài hát đã đăng': 'Published Songs',
  'Đã duyệt': 'Approved',
  'Chờ duyệt': 'Pending',
  'Bị chặn': 'Blocked',
  'Bạn chưa tải lên bài hát nào.': 'You haven\'t uploaded any songs yet.',

  // FullscreenPlayer
  'Danh Sách Phát': 'Queue / Playlist',
  'Lời Bài Hát': 'Lyrics',
  'Chưa có lời cho bài hát này.': 'No lyrics available for this song.',
  'Chưa chọn bài hát nào': 'No song selected',
  'Quay lại trang chủ và nhấp vào một bài hát bất kỳ để bắt đầu thưởng thức âm nhạc.': 'Go back to Home and click any song to start enjoying music.',
  'Quay về trang chủ': 'Go back to Home',
  'Lời bài hát': 'Lyrics',
  'Không có lời bài hát cho tác phẩm này.': 'No lyrics available for this song.',

  // ArtistDashboard
  'Tổng quan nghệ sĩ': 'Artist Overview',
  'Phân tích chỉ số lượt nghe và quản lý bài hát đã tải lên.': 'Analyze listening metrics and manage uploaded songs.',
  'Tổng lượt nghe': 'Total Views',
  'Tổng số bài hát': 'Total Songs',
  'Đang tải dữ liệu...': 'Loading data...',
  'Tìm kiếm dữ liệu...': 'Search statistics...',
  'Đang tải số liệu thống kê...': 'Loading statistics...',
  'Phân tích Nghệ sĩ': 'Artist Analytics',
  '. Đây là những gì đang diễn ra với âm nhạc của bạn.': '. Here is what is happening with your music.',
  'Tiền bản quyền dự kiến': 'Estimated Royalties',
  'Hạn mức: 10GB': 'Limit: 10GB',
  'Dung lượng sử dụng': 'Storage Used',
  'Tăng trưởng Khán giả': 'Audience Growth',
  'Tuần 1': 'Week 1',
  'Tuần 2': 'Week 2',
  'Tuần 3': 'Week 3',
  'Tuần 4': 'Week 4',
  'Lượt nghe theo tháng': 'Views by Month',
  'Th1': 'Jan',
  'Th2': 'Feb',
  'Th3': 'Mar',
  'Th4': 'Apr',
  'Th5': 'May',
  'Th6': 'Jun',
  'Các bài hát của tôi': 'My Songs',
  'Quản lý tải lên': 'Manage Uploads',
  'Trạng thái': 'Status',
  'Đã phát hành': 'Published',
  'Không có bài hát nào được tìm thấy. Tải nhạc ngay!': 'No songs found. Upload music now!',
  
  // AdminDashboard
  'Bảng điều khiển Admin': 'Admin Dashboard',
  'Quản lý người dùng, bài hát và hệ thống Melodies.': 'Manage users, songs, and the Melodies system.',
  'Tổng người dùng': 'Total Users',
  'Đang tải dữ liệu admin...': 'Loading admin data...',
  'Quản lý bài hát': 'Manage Songs',
  'Quản lý người dùng': 'Manage Users',
  'Vai trò': 'Role',
  'Ngày tạo': 'Created Date',
  'Xóa người dùng': 'Delete User',
  'Bạn có chắc chắn muốn xóa người dùng này không?': 'Are you sure you want to delete this user?',
  'Xóa người dùng thành công!': 'Deleted user successfully!',
  'Phê duyệt bài hát thất bại.': 'Approving song failed.',
  'Chặn bài hát thất bại.': 'Blocking song failed.',
  'Phê duyệt đồng loạt gặp sự cố.': 'Bulk approval failed.',
  'Tìm kiếm hệ thống...': 'Search system...',
  'Đang tải bảng điều khiển Admin...': 'Loading admin dashboard...',
  'Hệ thống Quản trị': 'Administration System',
  'Giám sát thời gian thực và điều phối nội dung Melodies.': 'Real-time monitoring and moderation of Melodies content.',
  'Người dùng': 'Users',
  'Lượt stream': 'Streams',
  'Tải CPU hệ thống': 'System CPU Load',
  'Tối ưu': 'Optimal',
  'Hạ tầng Toàn cầu': 'Global Infrastructure',
  'Thời gian hoạt động (Uptime) trong 24 giờ qua': 'Uptime in the last 24 hours',
  'Tuần này': 'This week',
  'Thời gian thực': 'Real-time',
  'Sự cố Bảo mật': 'Security Incidents',
  'Hàng đợi Kiểm duyệt Nội dung': 'Content Moderation Queue',
  'Đang chờ xử lý': 'Pending',
  'mục': 'items',
  'Phê duyệt tất cả': 'Approve All',
  'Tác phẩm': 'Track',
  'Chặn bài hát': 'Block song',
  'Phê duyệt bài hát': 'Approve song',
  'Sạch sẽ! Không có bài hát nào đang chờ kiểm duyệt.': 'All clean! No songs pending moderation.',
  
  // Extra words often used
  'lượt nghe': 'views',
  'bài hát': 'songs',
  'Thành công': 'Success',
  'Thất bại': 'Failed',
  'Quay lại': 'Go back',
  'Hủy': 'Cancel'
};

export const LanguageProvider = ({ children }) => {
  // Default language is English ('en') as requested
  const [language, setLangState] = useState(() => {
    return localStorage.getItem('lang') || 'en';
  });

  const setLanguage = (lang) => {
    if (lang === 'en' || lang === 'vi') {
      setLangState(lang);
      localStorage.setItem('lang', lang);
    }
  };

  const t = (text) => {
    if (language === 'vi') {
      return text;
    }
    // For English, return translated if exists, else text
    return dictionary[text] || text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
