import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    home: 'Home',
    search: 'Search',
    library: 'Library',
    notifications: 'Notifications',
    settings: 'Settings',
    premium: 'Premium Plans',
    lyrics: 'Lyrics',
    queue: 'Queue',
    playing_ad: 'Ad playing. Controls disabled.',
    free_banner: 'Ad-supported session. Upgrade to Premium for 320kbps & download DRM files!',
    login: 'Log In',
    register: 'Sign Up',
    logout: 'Log Out',
    active: 'Active',
    inactive: 'Inactive',
    cancel_premium: 'Cancel Premium',
    billing_and_plans: 'Billing & Subscription',
    billing_subtitle: 'Manage your payment methods and transaction history.',
    current_method: 'Current Method',
    verified: 'Verified',
    remove: 'Remove',
    change: 'Change',
    add_new_method: 'Add New Method',
    vnpay_desc: 'Pay via QR or bank applications.',
    credit_card: 'Credit / Debit Card',
    credit_card_desc: 'Visa, Mastercard, JCB international support.',
    other_methods: 'Other Methods',
    connect_now: 'Connect Now',
    add_card: 'Add Card',
    transaction_history: 'Transaction History',
    download_invoice: 'Download invoice (.pdf)',
    table_desc: 'Description',
    table_date: 'Transaction Date',
    table_amount: 'Amount',
    table_status: 'Status',
    success: 'Success',
    failed: 'Failed',
    need_help: 'Need Payment Help?',
    help_desc: 'Our 24/7 support team is always ready to help you resolve transaction issues.',
    contact_now: 'Contact Now',
    premium_cancelled_notice: 'Your Premium subscription has been cancelled and will expire on {date}. After this date, your account will automatically revert to Free.',
    reactivate_renew: 'Reactivate Auto-renew',
    artist_dashboard: 'Artist Studio',
    admin_dashboard: 'Admin Control',
    recent_plays: 'Recently Played',
    featured: 'Featured Playlists',
    artists: 'Artists to Follow',
    waveform: 'Waveform Progress',
    search_placeholder: 'Search songs, artists, albums...',
    moderation_queue: 'Moderation Queue',
    ad_campaigns: 'Ad Campaigns',
    subscriptions: 'Subscriptions',
    welcome: 'Welcome back',
    download_drm: 'Download DRM Binary',
    upload_songs: 'Upload Songs',
    profanity_hidden: 'Hidden comments (profanity flagged)',
    
    // Home Page
    loading_homepage: 'Loading homepage...',
    explore_categories: 'Explore Genres',
    recommended_songs: 'Recommended Songs',
    artists_recommendation: 'Recommended Artists',
    followers: 'followers',
    
    // Search Results / Details
    no_exact_results_fuzzy: 'No exact matches found. Here are some suggestions:',
    found: 'Found',
    matching_songs_count: 'matching songs.',
    searching: 'Searching...',
    did_you_mean: 'Did you mean / Top recommendations:',
    related_artists: 'Related Artists',
    no_matching_results: 'No matching results found',
    try_other_keywords: 'Try searching with other keywords or genres.',
    suggested_query_prefix: 'No exact results for',
    suggested_query_prompt: 'Did you mean:',
    showing_results_for: 'Showing results for',
    
    // Library
    music_library: 'Music Library',
    library_subtitle: 'Keep your personal playlists and favorite songs in one place.',
    create_playlist: 'Create New Playlist',
    liked_songs: 'Liked Songs',
    liked_songs_desc: 'Your collection of top favorite tracks.',
    songs_count: 'songs',
    songs: 'songs',
    no_description: 'No description',
    playlist_name: 'Playlist Name',
    short_description: 'Short Description',
    playlist_desc_placeholder: 'Describe your playlist...',
    privacy: 'Privacy',
    public: 'Public',
    private: 'Private',
    cancel: 'Cancel',
    create: 'Create',
    
    // Playlist Detail
    liked_songs_playlist_desc: 'Collection of all tracks you liked.',
    playlist_not_found: 'Playlist not found.',
    songs_list: 'Songs List',
    remove_track: 'Remove Track',
    no_songs_in_playlist: 'No songs in this playlist.',
    
    // Artist Detail
    artist_not_found: 'Artist profile not found.',
    all_songs: 'All Releases',
    no_songs_by_artist: 'This artist has not uploaded any songs yet.',
    
    // Settings
    account_settings: 'Account Settings',
    settings_subtitle: 'Update your profile information and manage premium subscriptions.',
    profile_updated: 'Profile updated successfully!',
    email_disabled: 'Email',
    fullname: 'Full Name',
    avatar_url: 'Avatar URL',
    avatar_url_placeholder: 'Enter image URL path...',
    purchase_transactions: 'Purchase Transactions',
    view_payment_history: 'View Payment History',
    save_changes: 'Save Changes',
    update_password: 'Update Password',
    manage_experience: 'Manage your experience',
    upgrade_to_premium_badge: 'Upgrade to Premium',
    account_info: 'Account Information',
    update_profile_desc: 'Update your public profile and personal details.',
    joined_date: 'Joined Melodies in 2024',
    change_photo: 'Change Photo',
    uploading: 'Uploading...',
    change: 'Change',
    security_desc: "Keep your Melodies account secure. We recommend using a unique password that you don't use on other services.",
    password_requirements: 'Password Requirements',
    req_min_chars: '8+ characters minimum',
    req_uppercase: 'At least one uppercase letter',
    req_number_symbol: 'At least one number or symbol',
    req_match: 'Matches confirmation field',
    pro_tip: 'Pro Tip',
    '2fa_tip_desc': 'Consider enabling Two-Factor Authentication (2FA) for an extra layer of security beyond your password.',
    configure_2fa: 'Configure 2FA',
    password_updated_success: 'Password updated successfully!',
    new_password_placeholder: 'New password',
    confirm_password_placeholder: 'Confirm password',
    security: 'Security',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_new_password: 'Confirm New Password',
    danger_zone: 'Danger Zone',
    delete_account_desc: 'Permanently delete your account and all of your data. This action is irreversible.',
    delete_account: 'Delete Account',
    confirm_delete_account: 'WARNING: This action is irreversible. Are you sure you want to permanently delete your account?',
    confirm_cancel_premium: 'Are you sure you want to cancel the auto-renewal of your Premium plan?',
    msg_cancel_premium_success: 'Auto-renewal cancelled successfully. Your Premium plan will remain active until the expiration date.',
    msg_reactivate_premium_success: 'Auto-renewal reactivated successfully!',
    err_password_mismatch: 'Confirm password does not match.',
    premium_monthly_desc: 'Monthly Premium Plan — 59,000 VND / month',
    free_plan_desc: 'Ad-supported streaming session plan.',
    next_billing_date: 'Next billing date',
    no_payment_method: 'No payment method linked.',
    setup_payment: 'Set up payment',
    last_linked_prefix: 'Last linked:',
    payment_method_removed: 'Payment method removed successfully.',
    loading_invoices: 'Loading invoices...',
    change_email: 'Change Email',
    enter_new_email_desc: 'Enter the new email address you want to use for your Melodies account.',
    new_email_label: 'New Email',
    sending_code: 'Sending...',
    send_verification_code: 'Send Verification Code',
    verify_new_email: 'Verify New Email',
    otp_sent_new_email_desc: 'We have sent a 6-digit verification code to your new email. Please enter the code below.',
    confirming: 'Confirming...',
    confirm_change: 'Confirm Change',
    no_code_received: 'Did not receive code?',
    resend_code: 'Resend Code',
    email_change_success: 'Email changed successfully!',
    email_updated_notice: 'Your email address has been updated. You will need to use this new email to log in next time.',
    back_to_profile: 'Back to Profile',
    premium_personal_1m: 'Individual Premium Plan (1 Month)',
    date_history_1: '12 Sep, 2023',
    date_history_2: '12 Aug, 2023',
    date_history_3: '12 Jul, 2023',
    '12 Th08, 2023': '12 Aug, 2023',
    
    // Subscription Plans
    upgrade_premium: 'Upgrade Your Premium Plan',
    btn_upgrade_premium: 'Upgrade Premium',
    subscription_subtitle: 'Unlock superior audio quality. Choose your plan to support artists.',
    choose_gateway: 'Choose Payment Gateway',
    momo_wallet: 'MoMo Wallet',
    vnpay_gateway: 'VNPAY Gateway',
    loading_plans: 'Loading subscription plans...',
    popular: 'Popular',
    vnd_per_month: 'VND / Month',
    default_plan: 'Default',
    upgrade_now: 'Upgrade Now',
    already_free: 'Your account is already on the default Free plan.',
    payment_failed: 'Payment request failed: ',
    payment_success: 'Payment Successful',
    payment_pending: 'Awaiting Payment',
    simulated_transaction_prefix: 'Simulating Transaction via',
    order_id_label: 'Order ID:',
    payment_method_label: 'Payment Method:',
    amount_label: 'Amount:',
    plan_duration_label: 'Plan Duration:',
    not_updated: 'Not updated',
    e_wallet: 'E-Wallet',
    duration_30_days: '30 days (From activation)',
    scan_qr_desc: 'Scan the QR code with a simulated app or click the button below to complete transaction.',
    confirm_payment_success: 'Confirm Payment Success',
    start_listening_premium: 'Start Listening to Premium',
    'Payment verified successfully and Premium membership activated!': 'Payment verified successfully and Premium membership activated!',
    'Payment verification failed': 'Payment verification failed',
    'Transaction not found': 'Transaction not found',
    'Transaction already processed': 'Transaction already processed',
    
    // Seeded Plan content translations
    'Trải nghiệm nghe nhạc trực tuyến miễn phí': 'Experience free streaming music online',
    'Nghe nhạc cơ bản': 'Basic music listening',
    'Có chèn Audio Ads quảng cáo': 'With Audio Ads inserted',
    'Chất lượng tiêu chuẩn 128kbps': 'Standard 128kbps quality',
    'Tải DRM bị khóa': 'DRM downloads locked',
    'Mở khóa âm nhạc chất lượng cao đỉnh cao': 'Unlock high quality premium audio',
    'Không quảng cáo (Ad-free)': 'Ad-free',
    'Tải nhạc bản quyền DRM Offline': 'Download DRM Offline music',
    'Chất lượng cao 320kbps': 'High quality 320kbps',
    'Âm thanh không nén lossless': 'Lossless audio streaming',
    'Miễn phí': 'Free',
    'Trải nghiệm cơ bản': 'Basic Experience',
    'Nghe hàng triệu bài hát': 'Listen to millions of songs',
    'Tạo playlist cá nhân': 'Create personal playlists',
    'Có quảng cáo xen kẽ': 'With ads included',
    'Chất lượng âm thanh tiêu chuẩn': 'Standard sound quality',
    'Dành cho Audiophile': 'For Audiophile',
    'Không quảng cáo': 'Ad-free',
    'Âm thanh 320kbps cực đỉnh': 'Premium 320kbps sound',
    'Tải nhạc nghe Offline': 'Download music for offline listening',
    'Chuyển bài không giới hạn': 'Unlimited skips',
    'Hỗ trợ đa thiết bị': 'Multi-device support',
    
    // Forgot Password
    forgot_password: 'Forgot Password',
    forgot_password_desc: 'Enter your email address to receive a recovery code.',
    send_recovery_code: 'Send Recovery Code',
    back_to_login: 'Back to Log In',
    verify_otp_title: 'Verify OTP',
    verify_otp_desc: 'Enter the 6-digit OTP code sent to your email.',
    verify_code_btn: 'Verify Code',
    reset_password_title: 'Reset Password',
    reset_password_desc: 'Enter a new password for your account.',
    set_new_password_btn: 'Reset Password',
    
    // Artist Dashboard & Upload Manage
    artist_dashboard_title: 'Artist Channel: Creator Studio',
    artist_dashboard_subtitle: 'Manage uploaded songs, track streams, and fan growth metrics.',
    upload_new_song_btn: 'Upload New Release',
    loading_analytics: 'Loading analytics...',
    total_streams: 'Total Streams',
    total_likes: 'Total Likes',
    artist_followers: 'Followers',
    weekly_trends: 'Weekly Streaming Trends',
    weekly_trends_desc: 'Displaying daily cumulative stream statistics.',
    day_mon: 'Mon',
    day_tue: 'Tue',
    day_wed: 'Wed',
    day_thu: 'Thu',
    day_fri: 'Fri',
    day_sat: 'Sat',
    day_sun: 'Sun',
    your_releases: 'Your Releases',
    table_song: 'Track',
    table_genre: 'Genre',
    table_streams: 'Streams',
    table_likes: 'Likes',
    table_status: 'Status',
    no_songs_uploaded: 'No songs have been uploaded yet.',
    upload_new_release_title: 'Upload New Release',
    upload_release_desc: 'Upload MP3/WAV files up to 100MB. The system automatically encodes and distributes standard streams.',
    track_title_label: 'Track Title',
    track_title_placeholder: 'Enter track title',
    genre_label: 'Genre',
    other_genre_option: 'Other (Add new genre...)',
    custom_genre_label: 'Custom Genre',
    custom_genre_placeholder: 'Enter custom genre',
    lyrics_label: 'Lyrics',
    lyrics_placeholder: 'Enter lyrics...',
    audio_file_label: 'Audio File (MP3, WAV)',
    drag_drop_select: 'Drag & drop or click to select',
    choose_file_btn: 'Choose File',
    uploading_audio: 'Uploading audio file...',
    upload_success: 'Uploaded successfully!',
    track_duration_label: 'Duration:',
    change_file_btn: 'Change file',
    failed_to_upload: 'failed to upload',
    please_retry_file: 'Please retry uploading',
    retry_upload_btn: 'Retry Upload',
    choose_other_file_btn: 'Choose other file',
    cover_image_label: 'Cover Image (1:1)',
    max_image_size: 'Maximum size 2MB',
    uploading_cover: 'Uploading cover image...',
    selected_cover: 'Selected cover',
    change_cover_btn: 'Change cover',
    publish_release_btn: 'Publish Release',
    publishing_loader: 'Converting & Publishing...',
    err_audio_large: 'Audio file exceeds 100MB limit.',
    err_image_large: 'Cover image exceeds 2MB limit.',
    err_invalid_audio: 'Please upload a valid audio file.',
    err_missing_title: 'Please enter a track title.',
    err_missing_genre: 'Please enter custom genre name.',
    err_upload_failed: 'Failed to upload song.',

    // Admin Dashboard Translations
    admin_dashboard_title: 'System Administration Studio',
    admin_dashboard_subtitle: 'Central hub to moderate songs, comments, run ad campaigns & configure plans.',
    tab_overview: 'Overview',
    tab_songs: 'Approve Songs',
    tab_comments: 'Hidden Comments',
    tab_ads: 'Ad Campaigns',
    tab_config: 'Plans & Config',
    stats_users: 'Total Users',
    stats_premium: 'Premium Members',
    stats_streams: 'Streams Count',
    stats_revenue: 'Premium Revenue',
    chart_title: 'Revenue & Streams Graph',
    chart_subtitle: 'Displaying daily streaming metrics for the past week.',
    song_requests_title: 'Song Approval Queue',
    song_artist_prefix: 'Artist:',
    approve_btn: 'Approve',
    reject_btn: 'Reject',
    no_songs_in_queue: 'No song approval requests in queue.',
    hidden_comments_title: 'Comments Filtered Due to Profanity',
    table_user: 'User',
    table_comment_content: 'Comment Content',
    table_actions: 'Action',
    show_comment_btn: 'Restore',
    delete_comment_btn: 'Delete',
    no_flagged_comments: 'No flagged comments found.',
    ads_campaigns_title: 'Visual / Audio Advertisement Campaigns',
    create_new_ad_btn: 'Create New Ad',
    table_ad_name: 'Campaign Name',
    table_ad_type: 'Type',
    table_ad_client: 'Client',
    table_ad_impressions: 'Impressions',
    table_ad_clicks: 'Clicks',
    table_ad_budget: 'Budget',
    action_stop: 'Stop',
    action_start: 'Start',
    no_ads_setup: 'No advertisement campaigns configured.',
    create_ad_modal_title: 'Create New Ad Campaign',
    label_ad_title: 'Campaign Name',
    label_ad_type: 'Ad Type',
    option_ad_audio: 'Audio Ad (Sound)',
    option_ad_banner: 'Banner Ad (Display)',
    label_ad_budget: 'Budget Limit (USD)',
    label_ad_client: 'Client Partner',
    label_ad_audio_url: 'Audio File Path (URL)',
    label_ad_image_url: 'Banner Image Path (URL)',
    label_ad_target_url: 'Destination Link (On Click)',
    btn_cancel: 'Cancel',
    btn_activate: 'Activate',
    plan_config_title: 'Pricing Plan Management',
    plan_config_subtitle: 'Directly modify subscription values for account tiers.',
    sandbox_payment_title: 'Payment Gateway Configuration',
    sandbox_payment_subtitle: 'Configure Merchant ID & Secret parameters for transaction networks.',
    btn_update_momo: 'Update Momo Config',
    btn_update_vnpay: 'Update VNPay Config',
    loading_dashboard_modules: 'Loading dashboard modules...',
    msg_momo_updated: 'Momo credentials updated successfully!',
    msg_vnpay_updated: 'VNPay credentials updated successfully!',
    msg_plan_updated: 'Pricing plan updated successfully!',
    msg_comment_approved: 'Comment approved and restored.',
    msg_comment_deleted: 'Comment deleted successfully.',
    msg_song_approved: 'Song approved successfully.',
    msg_song_banned: 'Song rejected and banned.',
    confirm_delete_ad: 'Are you sure you want to delete this ad campaign?',
    pricing_plans_badge: 'PRICING PLANS',
    pricing_title_line1: 'Supreme Audio Quality',
    pricing_title_line2: 'Unlimited Experience',
    pricing_desc: 'Choose the subscription plan that fits your style. Upgrade to Premium to unlock the best sound quality.',
    current_plan: 'CURRENT PLAN',
    use_free: 'USE FOR FREE',
    upgrade_now_btn: 'UPGRADE NOW',
    feature_comparison: 'Feature Comparison',
    feature: 'Feature',
    faq_title: 'Frequently Asked Questions',
    faq_cancel_anytime_q: 'Can I cancel my subscription at any time?',
    faq_cancel_anytime_a: 'Yes, you can cancel your Premium plan at any time in your account settings. After canceling, you will still be able to use Premium features until the end of your current billing cycle.',
    faq_how_to_pay_q: 'How do I pay?',
    faq_how_to_pay_a: 'Melodies supports payments via MoMo Wallet and VNPAY gateway. All transactions are securely processed through sandbox systems, ensuring instant upgrades.',
    already_premium: 'Your account is already Premium!',
    'Thư viện nhạc bản quyền': 'Licensed music library',
    'Nghe nhạc không quảng cáo': 'Ad-free listening',
    'Chất lượng âm thanh': 'Audio quality',
    'Tải về nghe Offline': 'Offline downloads'
  },
  vi: {
    home: 'Trang chủ',
    search: 'Tìm kiếm',
    library: 'Thư viện',
    notifications: 'Thông báo',
    settings: 'Cài đặt',
    premium: 'Gói Premium',
    lyrics: 'Lời bài hát',
    queue: 'Hàng đợi',
    playing_ad: 'Quảng cáo đang phát. Đã vô hiệu hóa các nút tua/chuyển bài.',
    free_banner: 'Phiên bản miễn phí có quảng cáo. Nâng cấp Premium để nghe nhạc 320kbps & tải DRM!',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    logout: 'Đăng xuất',
    active: 'Đang hoạt động',
    inactive: 'Chưa kích hoạt',
    cancel_premium: 'Hủy gói Premium',
    billing_and_plans: 'Thanh toán & Gói cước',
    billing_subtitle: 'Quản lý phương thức thanh toán và lịch sử giao dịch của bạn.',
    current_method: 'Phương thức hiện tại',
    verified: 'Đã xác thực',
    remove: 'Gỡ bỏ',
    change: 'Thay đổi',
    add_new_method: 'Thêm phương thức mới',
    vnpay_desc: 'Thanh toán qua QR hoặc ứng dụng ngân hàng.',
    credit_card: 'Thẻ Tín dụng / Ghi nợ',
    credit_card_desc: 'Visa, Mastercard, JCB hỗ trợ quốc tế.',
    other_methods: 'Phương thức khác',
    connect_now: 'Kết nối ngay',
    add_card: 'Thêm thẻ',
    transaction_history: 'Lịch sử giao dịch',
    download_invoice: 'Tải hóa đơn (.pdf)',
    table_desc: 'Mô tả',
    table_date: 'Ngày giao dịch',
    table_amount: 'Số tiền',
    table_status: 'Trạng thái',
    success: 'Thành công',
    failed: 'Thất bại',
    need_help: 'Cần hỗ trợ thanh toán?',
    help_desc: 'Đội ngũ hỗ trợ 24/7 của chúng tôi luôn sẵn sàng giúp bạn giải quyết các vấn đề về giao dịch.',
    contact_now: 'Liên hệ ngay',
    premium_cancelled_notice: 'Gói Premium của bạn đã được hủy gia hạn và sẽ hết hiệu lực vào ngày {date}. Sau ngày này, tài khoản của bạn sẽ tự động quay về gói Free.',
    reactivate_renew: 'Gia hạn lại',
    artist_dashboard: 'Kênh Nghệ sĩ',
    admin_dashboard: 'Kênh Admin',
    recent_plays: 'Nghe gần đây',
    featured: 'Danh sách phát nổi bật',
    artists: 'Nghệ sĩ đề xuất',
    waveform: 'Tiến trình sóng âm',
    search_placeholder: 'Tìm kiếm bài hát, nghệ sĩ, album...',
    moderation_queue: 'Danh sách kiểm duyệt',
    ad_campaigns: 'Quảng cáo & Ads',
    subscriptions: 'Cài đặt gói cước',
    welcome: 'Chào mừng trở lại',
    download_drm: 'Tải file DRM',
    upload_songs: 'Tải lên bài hát',
    profanity_hidden: 'Bình luận bị ẩn (chứa từ nhạy cảm)',
    
    // Home Page
    loading_homepage: 'Tải trang chủ...',
    explore_categories: 'Khám phá Thể loại',
    recommended_songs: 'Bài hát đề xuất',
    artists_recommendation: 'Gợi ý Nghệ sĩ',
    followers: 'người theo dõi',
    
    // Search Results / Details
    no_exact_results_fuzzy: 'Không tìm thấy kết quả phù hợp chính xác. Dưới đây là các gợi ý dành cho bạn:',
    found: 'Tìm thấy',
    matching_songs_count: 'bài hát phù hợp.',
    searching: 'Đang tìm kiếm...',
    did_you_mean: 'Ý bạn là / Đề xuất hàng đầu:',
    related_artists: 'Nghệ sĩ liên quan',
    no_matching_results: 'Không tìm thấy kết quả nào phù hợp',
    try_other_keywords: 'Hãy thử tìm kiếm với các từ khóa hoặc thể loại khác.',
    suggested_query_prefix: 'Không tìm thấy kết quả chính xác cho',
    suggested_query_prompt: 'Có phải bạn muốn tìm:',
    showing_results_for: 'Hiển thị kết quả cho',
    
    // Library
    music_library: 'Thư viện Âm nhạc',
    library_subtitle: 'Nơi lưu giữ các danh sách phát cá nhân của bạn và danh sách các bài hát yêu thích.',
    create_playlist: 'Tạo Playlist mới',
    liked_songs: 'Bài hát Đã thích',
    liked_songs_desc: 'Danh sách lưu trữ các bài hát tâm đắc nhất của bạn.',
    songs_count: 'Bài hát',
    songs: 'bài hát',
    no_description: 'Không có mô tả',
    playlist_name: 'Tên Playlist',
    short_description: 'Mô tả ngắn',
    playlist_desc_placeholder: 'Mô tả danh sách phát của bạn...',
    privacy: 'Quyền riêng tư',
    public: 'Công khai / Public',
    private: 'Riêng tư / Private',
    cancel: 'Hủy',
    create: 'Tạo mới',
    
    // Playlist Detail
    liked_songs_playlist_desc: 'Tuyển tập tất cả các tác phẩm bạn đã bấm yêu thích.',
    playlist_not_found: 'Không tìm thấy danh sách phát.',
    songs_list: 'Danh sách bài hát',
    remove_track: 'Xóa bài',
    no_songs_in_playlist: 'Không có bài hát nào trong playlist này.',
    
    // Artist Detail
    artist_not_found: 'Không tìm thấy thông tin Nghệ sĩ.',
    all_songs: 'Tất cả sản phẩm',
    no_songs_by_artist: 'Nghệ sĩ này chưa đăng tải tác phẩm nào.',
    
    // Settings
    account_settings: 'Thiết lập Tài khoản',
    settings_subtitle: 'Cập nhật thông tin định danh và quản lý các giao dịch nâng cấp Premium.',
    profile_updated: 'Thông tin tài khoản đã được cập nhật thành công!',
    email_disabled: 'Email',
    fullname: 'Họ và Tên',
    avatar_url: 'Ảnh đại diện (URL)',
    avatar_url_placeholder: 'Nhập đường dẫn URL hình ảnh...',
    purchase_transactions: 'Giao dịch mua hàng',
    view_payment_history: 'Xem Lịch sử Giao dịch',
    save_changes: 'Lưu thay đổi',
    update_password: 'Cập nhật Mật khẩu',
    manage_experience: 'Quản lý trải nghiệm của bạn',
    upgrade_to_premium_badge: 'Nâng cấp Premium',
    account_info: 'Thông tin tài khoản',
    update_profile_desc: 'Cập nhật hồ sơ công khai và thông tin cá nhân của bạn.',
    joined_date: 'Tham gia Melodies từ năm 2024',
    change_photo: 'Thay đổi ảnh',
    uploading: 'Đang tải lên...',
    change: 'Thay đổi',
    security_desc: 'Giữ tài khoản Melodies của bạn an toàn. Chúng tôi khuyên bạn nên sử dụng mật khẩu duy nhất không trùng lặp.',
    password_requirements: 'Yêu cầu mật khẩu',
    req_min_chars: 'Tối thiểu 8 ký tự',
    req_uppercase: 'Ít nhất một chữ cái viết hoa',
    req_number_symbol: 'Ít nhất một chữ số hoặc ký hiệu',
    req_match: 'Khớp với trường xác nhận',
    pro_tip: 'Gợi ý bảo mật',
    '2fa_tip_desc': 'Hãy cân nhắc bật Xác thực hai yếu tố (2FA) để thêm lớp bảo mật bổ sung ngoài mật khẩu.',
    configure_2fa: 'Cấu hình 2FA',
    password_updated_success: 'Mật khẩu đã được cập nhật thành công!',
    new_password_placeholder: 'Mật khẩu mới',
    confirm_password_placeholder: 'Xác nhận mật khẩu',
    security: 'Bảo mật',
    current_password: 'Mật khẩu Hiện tại',
    new_password: 'Mật khẩu Mới',
    confirm_new_password: 'Xác nhận Mật khẩu Mới',
    danger_zone: 'Vùng Nguy hiểm',
    delete_account_desc: 'Xóa vĩnh viễn tài khoản của bạn và toàn bộ dữ liệu. Hành động này không thể khôi phục.',
    delete_account: 'Xóa Tài khoản',
    confirm_delete_account: 'CẢNH BÁO: Hành động này không thể hoàn tác. Bạn có chắc muốn xóa vĩnh viễn tài khoản của mình?',
    confirm_cancel_premium: 'Bạn có chắc chắn muốn hủy gia hạn tự động gói Premium?',
    msg_cancel_premium_success: 'Đã hủy tự động gia hạn thành công. Gói Premium của bạn vẫn hoạt động đến ngày hết hạn.',
    msg_reactivate_premium_success: 'Đã kích hoạt lại tự động gia hạn gói Premium thành công!',
    err_password_mismatch: 'Mật khẩu xác nhận không khớp.',
    premium_monthly_desc: 'Gói Premium hàng tháng — 59.000 VND / tháng',
    free_plan_desc: 'Gói nghe nhạc cơ bản có chèn quảng cáo.',
    next_billing_date: 'Ngày gia hạn tiếp theo',
    no_payment_method: 'Chưa liên kết phương thức thanh toán.',
    setup_payment: 'Thiết lập thanh toán',
    last_linked_prefix: 'Liên kết lần cuối:',
    payment_method_removed: 'Đã gỡ phương thức thanh toán thành công.',
    loading_invoices: 'Đang tải hóa đơn...',
    change_email: 'Thay đổi Email',
    enter_new_email_desc: 'Nhập địa chỉ email mới mà bạn muốn sử dụng cho tài khoản Melodies.',
    new_email_label: 'Email mới',
    sending_code: 'Đang gửi...',
    send_verification_code: 'Gửi mã xác thực',
    verify_new_email: 'Xác thực Email mới',
    otp_sent_new_email_desc: 'Chúng tôi đã gửi mã xác thực 6 chữ số đến email mới của bạn. Vui lòng nhập mã bên dưới.',
    confirming: 'Đang xác nhận...',
    confirm_change: 'Xác nhận thay đổi',
    no_code_received: 'Không nhận được mã?',
    resend_code: 'Gửi lại mã',
    email_change_success: 'Thay đổi Email thành công!',
    email_updated_notice: 'Địa chỉ email của bạn đã được cập nhật. Bạn sẽ cần sử dụng email mới này để đăng nhập vào lần sau.',
    back_to_profile: 'Quay lại Hồ sơ',
    premium_personal_1m: 'Gói Premium Cá nhân (1 Tháng)',
    date_history_1: '12 Th09, 2023',
    date_history_2: '12 Th08, 2023',
    date_history_3: '12 Th07, 2023',
    '12 Th08, 2023': '12 Th08, 2023',
    
    // Subscription Plans
    upgrade_premium: 'Nâng cấp Gói Premium của bạn',
    btn_upgrade_premium: 'Nâng cấp Premium',
    'Miễn phí': 'Miễn phí',
    'Trải nghiệm cơ bản': 'Trải nghiệm cơ bản',
    'Nghe hàng triệu bài hát': 'Nghe hàng triệu bài hát',
    'Tạo playlist cá nhân': 'Tạo playlist cá nhân',
    'Có quảng cáo xen kẽ': 'Có quảng cáo xen kẽ',
    'Chất lượng âm thanh tiêu chuẩn': 'Chất lượng âm thanh tiêu chuẩn',
    'Dành cho Audiophile': 'Dành cho Audiophile',
    'Không quảng cáo': 'Không quảng cáo',
    'Âm thanh 320kbps cực đỉnh': 'Âm thanh 320kbps cực đỉnh',
    'Tải nhạc nghe Offline': 'Tải nhạc nghe Offline',
    'Chuyển bài không giới hạn': 'Chuyển bài không giới hạn',
    'Hỗ trợ đa thiết bị': 'Hỗ trợ đa thiết bị',
    subscription_subtitle: 'Tự hào nâng tầm chất lượng âm nhạc vượt trội. Lựa chọn gói cước phù hợp và hỗ trợ các nghệ sĩ bạn yêu quý.',
    choose_gateway: 'Chọn cổng kết nối thanh toán',
    momo_wallet: 'Ví MoMo',
    vnpay_gateway: 'Cổng VNPAY',
    loading_plans: 'Tải danh sách các gói cước...',
    payment_success: 'Đã Thanh toán thành công',
    payment_pending: 'Đang chờ Thanh toán',
    simulated_transaction_prefix: 'Mô phỏng Giao dịch thông qua Cổng',
    order_id_label: 'Mã Đơn hàng:',
    payment_method_label: 'Phương thức:',
    amount_label: 'Số tiền:',
    plan_duration_label: 'Thời hạn gói:',
    not_updated: 'Chưa cập nhật',
    e_wallet: 'Ví Điện Tử',
    duration_30_days: '30 ngày (Kể từ khi kích hoạt)',
    scan_qr_desc: 'Quét mã QR bằng ứng dụng MoMo/VNPay giả lập hoặc click nút bên dưới để hoàn tất giao dịch.',
    confirm_payment_success: 'Xác nhận đã chuyển khoản thành công',
    start_listening_premium: 'Bắt đầu nghe nhạc Premium',
    'Payment verified successfully and Premium membership activated!': 'Xác nhận thanh toán thành công, tài khoản Premium đã được kích hoạt!',
    'Payment verification failed': 'Xác nhận thanh toán thất bại',
    'Transaction not found': 'Không tìm thấy thông tin giao dịch',
    'Transaction already processed': 'Giao dịch này đã được xử lý trước đó',
    popular: 'Popular',
    vnd_per_month: 'VND / Tháng',
    default_plan: 'Mặc định',
    upgrade_now: 'Nâng cấp ngay',
    already_free: 'Tài khoản của bạn đã ở gói Miễn phí mặc định.',
    payment_failed: 'Tạo yêu cầu thanh toán thất bại: ',
    
    // Forgot Password
    forgot_password: 'Quên mật khẩu',
    forgot_password_desc: 'Nhập địa chỉ email của bạn để nhận mã khôi phục.',
    send_recovery_code: 'Gửi mã khôi phục',
    back_to_login: 'Quay lại Đăng nhập',
    verify_otp_title: 'Xác thực OTP',
    verify_otp_desc: 'Nhập mã OTP 6 chữ số đã được gửi đến email của bạn.',
    verify_code_btn: 'Xác thực mã',
    reset_password_title: 'Đặt lại mật khẩu',
    reset_password_desc: 'Nhập mật khẩu mới cho tài khoản của bạn.',
    set_new_password_btn: 'Đặt lại mật khẩu',
    
    // Artist Dashboard & Upload Manage
    artist_dashboard_title: 'Kênh Nghệ sĩ: Studio Sáng tạo',
    artist_dashboard_subtitle: 'Quản lý các bài hát đã tải lên, theo dõi thống kê lượt phát và chỉ số tăng trưởng người hâm mộ.',
    upload_new_song_btn: 'Tải lên tác phẩm mới',
    loading_analytics: 'Tải số liệu phân tích...',
    total_streams: 'Tổng lượt nghe',
    total_likes: 'Tổng lượt thích',
    artist_followers: 'Người theo dõi',
    weekly_trends: 'Xu hướng phát nhạc trong tuần',
    weekly_trends_desc: 'Biểu diễn số liệu thống kê lượt nghe tích lũy hàng ngày.',
    day_mon: 'Thứ 2',
    day_tue: 'Thứ 3',
    day_wed: 'Thứ 4',
    day_thu: 'Thứ 5',
    day_fri: 'Thứ 6',
    day_sat: 'Thứ 7',
    day_sun: 'Chủ Nhật',
    your_releases: 'Tác phẩm của bạn',
    table_song: 'Bài hát',
    table_genre: 'Thể loại',
    table_streams: 'Lượt nghe',
    table_likes: 'Yêu thích',
    table_status: 'Trạng thái',
    no_songs_uploaded: 'Chưa có bài hát nào được đăng tải.',
    upload_new_release_title: 'Tải lên Tác phẩm mới',
    upload_release_desc: 'Tải nhạc định dạng MP3/WAV dung lượng tối đa 100MB. Hệ thống sẽ tự động phân phối các luồng nén 128kbps/320kbps.',
    track_title_label: 'Tên bài hát / Track Title',
    track_title_placeholder: 'Nhập tên bài hát',
    genre_label: 'Thể loại / Genre',
    other_genre_option: 'Khác (Thêm thể loại mới...)',
    custom_genre_label: 'Nhập thể loại mới / Custom Genre',
    custom_genre_placeholder: 'Nhập thể loại nhạc mới',
    lyrics_label: 'Lời bài hát / Lyrics',
    lyrics_placeholder: 'Nhập lời bài hát...',
    audio_file_label: 'Tệp âm thanh (MP3, WAV)',
    drag_drop_select: 'Kéo thả hoặc nhấn vào để chọn',
    choose_file_btn: 'Chọn File',
    uploading_audio: 'Đang tải lên tệp âm thanh...',
    upload_success: 'Tải lên thành công!',
    track_duration_label: 'Độ dài:',
    change_file_btn: 'Thay đổi tệp',
    failed_to_upload: 'failed to upload',
    please_retry_file: 'Vui lòng thử lại tệp',
    retry_upload_btn: 'Upload lại',
    choose_other_file_btn: 'Chọn tệp khác',
    cover_image_label: 'Ảnh bìa bài hát (1:1)',
    max_image_size: 'Dung lượng tối đa 2MB',
    uploading_cover: 'Đang tải ảnh bìa...',
    selected_cover: 'Ảnh bìa đã chọn',
    change_cover_btn: 'Thay đổi ảnh bìa',
    publish_release_btn: 'Xuất bản tác phẩm',
    publishing_loader: 'Đang chuyển đổi & Tải lên...',
    err_audio_large: 'Tệp âm thanh vượt quá giới hạn dung lượng 100MB.',
    err_image_large: 'Tệp ảnh bìa vượt quá giới hạn dung lượng 2MB.',
    err_invalid_audio: 'Vui lòng tải lên tệp âm thanh hợp lệ.',
    err_missing_title: 'Vui lòng điền tên bài hát.',
    err_missing_genre: 'Vui lòng nhập tên thể loại mới.',
    err_upload_failed: 'Tải lên bài hát thất bại.',

    // Admin Dashboard Translations
    admin_dashboard_title: 'Kênh Quản trị Hệ thống',
    admin_dashboard_subtitle: 'Phân hệ trung tâm hỗ trợ duyệt kiểm duyệt tác phẩm, chiến dịch quảng cáo & quản lý giá cước cước phí.',
    tab_overview: 'Tổng quan',
    tab_songs: 'Duyệt bài hát',
    tab_comments: 'Bình luận ẩn',
    tab_ads: 'Chiến dịch Ads',
    tab_config: 'Gói cước & Cấu hình',
    stats_users: 'Người dùng',
    stats_premium: 'Hội viên Premium',
    stats_streams: 'Lượt Stream nhạc',
    stats_revenue: 'Doanh thu Premium',
    chart_title: 'Doanh thu & Số lượt Stream',
    chart_subtitle: 'Biểu đồ thể hiện sự gia tăng tương tác trong tuần qua.',
    song_requests_title: 'Yêu cầu phê duyệt bài hát',
    song_artist_prefix: 'Nghệ sĩ:',
    approve_btn: 'Phê duyệt',
    reject_btn: 'Gỡ bỏ',
    no_songs_in_queue: 'Không có yêu cầu duyệt bài hát nào ở hàng đợi.',
    hidden_comments_title: 'Bình luận bị ẩn do vi phạm từ tục tĩu',
    table_user: 'Người dùng',
    table_comment_content: 'Nội dung bình luận',
    table_actions: 'Hành động',
    show_comment_btn: 'Hiện',
    delete_comment_btn: 'Xóa bỏ',
    no_flagged_comments: 'Không phát hiện bình luận vi phạm nào.',
    ads_campaigns_title: 'Chiến dịch Quảng cáo hiển thị / Audio',
    create_new_ad_btn: 'Tạo Quảng cáo mới',
    table_ad_name: 'Tên Chiến dịch',
    table_ad_type: 'Mẫu',
    table_ad_client: 'Doanh nghiệp',
    table_ad_impressions: 'Hiển thị',
    table_ad_clicks: 'Click',
    table_ad_budget: 'Ngân sách',
    action_stop: 'Dừng',
    action_start: 'Chạy',
    no_ads_setup: 'Chưa thiết lập chiến dịch quảng cáo nào.',
    create_ad_modal_title: 'Tạo chiến dịch quảng cáo mới',
    label_ad_title: 'Tên chiến dịch',
    label_ad_type: 'Loại Quảng cáo',
    option_ad_audio: 'Audio Ad (Âm thanh)',
    option_ad_banner: 'Banner Ad (Hiển thị)',
    label_ad_budget: 'Giới hạn ngân sách (USD)',
    label_ad_client: 'Doanh nghiệp đối tác',
    label_ad_audio_url: 'Đường dẫn tệp Audio (URL)',
    label_ad_image_url: 'Đường dẫn ảnh Banner (URL)',
    label_ad_target_url: 'URL Đích (Khi Click)',
    btn_cancel: 'Hủy',
    btn_activate: 'Kích hoạt',
    plan_config_title: 'Quản lý biểu phí Gói dịch vụ',
    plan_config_subtitle: 'Thay đổi trực tiếp giá trị thanh toán của từng phân cấp tài khoản.',
    sandbox_payment_title: 'Cấu hình Cổng thanh toán Sandbox',
    sandbox_payment_subtitle: 'Thiết lập tham số chữ ký số Merchant & Secret của đối tác.',
    btn_update_momo: 'Cập nhật Momo Config',
    btn_update_vnpay: 'Cập nhật VNPay Config',
    loading_dashboard_modules: 'Tải phân hệ dữ liệu...',
    msg_momo_updated: 'Đã cập nhật cấu hình Momo!',
    msg_vnpay_updated: 'Đã cập nhật cấu hình VNPay!',
    msg_plan_updated: 'Đã cập nhật giá trị gói cước thành công!',
    msg_comment_approved: 'Bình luận đã được duyệt hiển thị lại.',
    msg_comment_deleted: 'Đã xóa bình luận thành công.',
    msg_song_approved: 'Đã duyệt bài hát thành công.',
    msg_song_banned: 'Đã từ chối bài hát thành công.',
    confirm_delete_ad: 'Bạn có chắc chắn muốn xóa chiến dịch quảng cáo này?',
    pricing_plans_badge: 'GÓI DỊCH VỤ',
    pricing_title_line1: 'Âm nhạc đỉnh cao',
    pricing_title_line2: 'Trải nghiệm không giới hạn',
    pricing_desc: 'Chọn gói cước phù hợp với phong cách nghe nhạc của bạn. Nâng cấp lên Premium để mở khóa chất lượng âm thanh tốt nhất.',
    current_plan: 'GÓI HIỆN TẠI',
    use_free: 'DÙNG MIỄN PHÍ',
    upgrade_now_btn: 'NÂNG CẤP NGAY',
    feature_comparison: 'So sánh tính năng',
    feature: 'Tính năng',
    faq_title: 'Câu hỏi thường gặp',
    faq_cancel_anytime_q: 'Tôi có thể hủy đăng ký bất cứ lúc nào không?',
    faq_cancel_anytime_a: 'Có, bạn có thể hủy gói Premium bất cứ lúc nào trong cài đặt tài khoản. Sau khi hủy, bạn vẫn sẽ được sử dụng các tính năng Premium cho đến hết chu kỳ thanh toán hiện tại.',
    faq_how_to_pay_q: 'Làm sao để thanh toán?',
    faq_how_to_pay_a: 'Melodies hỗ trợ thanh toán qua Ví MoMo và cổng VNPAY. Các giao dịch đều được thực hiện qua cổng sandbox bảo mật, giúp nâng cấp tức thì mà không lo lộ thông tin.',
    already_premium: 'Tài khoản của bạn đã là Premium rồi!',
    'Thư viện nhạc bản quyền': 'Thư viện nhạc bản quyền',
    'Nghe nhạc không quảng cáo': 'Nghe nhạc không quảng cáo',
    'Chất lượng âm thanh': 'Chất lượng âm thanh',
    'Tải về nghe Offline': 'Tải về nghe Offline'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'vi');

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
